[package]
name = "docpad"
version = "1.1.0"
description = "DOCPAD - Doc Alvers Mathe-Labor"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-window-state = "2"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
